# Generated by Django 5.2.5 on 2026-03-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
